# Generated by Django 3.0.3 on 2020-02-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
