# Generated by Django 3.0.3 on 2020-02-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_away_team_goals'),
        ('tournaments', '0002_auto_20200219_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.Group'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='kickoff',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('home win', 'home win'), ('away win', 'away win'), ('draw', 'draw')], default='draw', max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('first half', 'first half'), ('half time', 'half time'), ('second half', 'second half'), ('extra first half', 'extra first half'), ('extra second half', 'extra second half'), ('extra half time', 'extra half time'), ('tie breaker', 'tie breaker'), ('over', 'over'), ('abandoned', 'abandoned')], default='scheduled', max_length=32),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.Tournament'),
        ),
    ]
