# Generated by Django 3.0.3 on 2020-02-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20200219_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchphoto',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
