# Generated by Django 3.0.3 on 2020-02-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveSmallIntegerField(default=0)),
                ('time', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('is_own_goal', models.BooleanField(default=False)),
                ('assisted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='players.Player')),
            ],
        ),
    ]
