# Generated by Django 3.0.3 on 2020-02-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='tournament/logos')),
                ('venue', models.CharField(default='', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('completed', 'completed')], max_length=32)),
                ('type', models.CharField(choices=[('knock out', 'Knock Out'), ('league', 'League'), ('league cum knockout', 'League cum knockout')], max_length=32)),
                ('no_of_teams', models.PositiveIntegerField(default=0)),
                ('teams', models.ManyToManyField(related_name='teams', to='teams.Team')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team')),
            ],
        ),
    ]
