# Generated by Django 3.0.4 on 2020-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournament/logos'),
        ),
    ]
